# Test `IsolationForest` class

In [1]:
import sys
sys.path.append('..')
from model_reboot.EIF_reboot import IsolationForest
import numpy as np
from utils_reboot.datasets import Dataset


In [2]:
dataset = Dataset("wine", path = "../data/real/")
dataset.drop_duplicates()

## `IsolationForest`

In [4]:
I=IsolationForest(n_estimators=100)
I.fit(dataset.X)

12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12


In [5]:
I.compute_ids(dataset.X)

In [6]:
pred,y_hat=I.decision_function_single_tree(1,dataset.X,p=0.1)
pred.shape,y_hat.shape

((129,), (129,))

In [ ]:
I.trees[0].child_right

array([2, 4, 0, ..., 0, 0, 0])

In [7]:
I_gfi=I.global_importances(dataset.X,0.1)
I_gfi

100it [00:18,  5.35it/s]


array([1.45570221, 0.97099082, 1.37818928, 1.7536564 , 1.49118793,
       1.51978639, 1.63866458, 1.07169841, 1.48211212, 1.10904872,
       1.03238004, 1.20685246, 1.66380843])

In [ ]:
I_lfi=I.local_importances(dataset.X)
I_lfi.shape

100it [00:00, 4527.14it/s]


(129, 13)

In [ ]:
I_lfi

array([[2.11679796, 2.19843785, 2.36468396, ..., 2.48687102, 2.19714851,
        2.42024768],
       [2.05765032, 2.1998165 , 2.32671793, ..., 2.42303706, 2.2175737 ,
        2.39771027],
       [1.96467735, 2.0184398 , 1.92068693, ..., 1.99448833, 1.99556772,
        1.99653673],
       ...,
       [1.70429231, 1.63312108, 1.70005042, ..., 1.73846621, 1.72580915,
        1.70505336],
       [1.69108047, 1.62503564, 1.69465289, ..., 1.73949674, 1.72276136,
        1.687907  ],
       [1.41345508, 1.32777714, 1.35411284, ..., 1.32617925, 1.35448664,
        1.38890139]])

In [ ]:
I.ids[0]

array([166, 166, 172, 166, 172, 172, 171, 166, 176, 181,  64, 170, 107,
       151, 103,  15, 170,  60,  60, 169, 156, 171, 103,  61, 169, 171,
       103, 112,  79, 169,  96,   6, 169, 150,  79,  79,  91,  60, 141,
       170, 149,  60, 107,  60,  44,  32, 169, 143, 103, 152, 123, 169,
       143, 101, 128, 170,  43,  60,  60,  43, 170,  81,  47, 151, 101,
        37, 128,  60,  24, 116,  75, 151,  96,  17, 121, 123, 116,  38,
       108,  36,  75, 151,  82,  81, 143, 150, 170, 169,  79,  75, 143,
       151, 171,  79,  75, 169, 169, 123, 150, 151,  81,  80,  96, 103,
       155, 151, 169,  67, 171, 152, 150,  79, 157,  81, 156, 150,  79,
       170, 170, 169, 151,  79,  61, 152, 169, 169, 169, 169,  75])

### Comparison with `IsolationForest` sklearn

In [ ]:
tree0=I.trees[0]

In [ ]:
tree0.child_left

array([ 1, 89,  3, ...,  0,  0,  0])

## `ExtendedIsolationForest`

In [ ]:
EIF=ExtendedIsolationForest(True,n_estimators=100)
EIF.fit(dataset.X)

In [ ]:
EIF.compute_ids(dataset.X)
EIF.ids.shape

(100, 129)

In [ ]:
EIF.ids

array([[ 30,  31,  35, ...,  26,  26,  84],
       [ 21,  18,  15, ...,  54,  54,  31],
       [157,  98, 153, ..., 133, 133, 132],
       ...,
       [ 92,  66, 112, ...,  44,  42,  29],
       [ 33, 114,  31, ...,  25,  25,  52],
       [118, 118, 122, ..., 122, 122,  87]])

In [ ]:
EIF_gfi=EIF.global_importances(dataset.X,0.1)
EIF_gfi

100it [00:02, 40.01it/s]


array([1.67271613, 1.64173778, 1.65524775, 1.66227731, 1.65406996,
       1.64958674, 1.66474756, 1.64373386, 1.67219171, 1.61676494,
       1.74101965, 1.6012881 , 1.75877346])

In [ ]:
EIF_lfi=EIF.local_importances(dataset.X)

100it [00:00, 5743.50it/s]


In [ ]:
EIF_lfi

array([[2.44769697, 2.47997017, 2.45448764, ..., 2.45044323, 2.48685632,
        2.5815397 ],
       [2.47555306, 2.51422083, 2.38753942, ..., 2.51836443, 2.42452014,
        2.51691597],
       [1.72459869, 1.93104829, 1.78224356, ..., 1.89552033, 1.89017945,
        1.89102886],
       ...,
       [1.80857292, 1.88319028, 1.76836078, ..., 1.76868666, 1.89266212,
        1.8035168 ],
       [1.8055783 , 1.88364092, 1.79934564, ..., 1.75191364, 1.90196917,
        1.82021561],
       [1.38615387, 1.44930143, 1.4718864 , ..., 1.33971409, 1.37406503,
        1.4744906 ]])

## `IsolationForest` sklearn

In [ ]:
IF=IsolationForest(n_estimators=100)
IF.fit(dataset.X)

IsolationForest()

In [ ]:
est0=IF.estimators_[0]

In [ ]:
est0.tree_.children_left

array([ 1,  2,  3,  4,  5,  6,  7,  8, -1, -1, -1, 12, 13, -1, -1, 16, -1,
       -1, -1, 20, 21, 22, 23, -1, -1, -1, -1, -1, 29, 30, 31, -1, -1, 34,
       -1, 36, -1, -1, -1, 40, -1, 42, 43, -1, -1, -1, 47, 48, 49, 50, 51,
       52, 53, -1, -1, 56, -1, -1, -1, 60, -1, 62, -1, -1, 65, -1, -1, 68,
       69, 70, 71, 72, -1, -1, -1, -1, -1, 78, 79, 80, 81, -1, -1, -1, 85,
       86, -1, -1, 89, -1, -1, 92, -1, -1, 95, -1, -1], dtype=int64)